### ISSUE TITLE
allow arbitrary-length prefixes, delimited by `_`

### ISSUE THREAD

**Issue by coolaj86** [therootcompany/base62-token.js#6]
Right now the token string split function is hard-coded to expect a 4-character prefix string (i.e. `ghp_`).

However, since the `_` serves as a delimiter outside of the base62 alphabet, we should just split on that.

Easy beginner-level programmer task. Anyone is free to take it.

**Comment by pehunter** [comment]
Hi, so I tried to solve this and (hopefully) created a pull request for this project. This is my first time contributing to an open-source project so please let me know if it worked!

**Comment by MahmoudDawood** [comment]
Is this issue solved yet or should I try to tackle it?

**Comment by coolaj86** [comment]
Fixed in #8
